name: Run UI Tests

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout test repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests (Chrome)
        run: ./gradlew test -Dselenium.browser=chrome

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests
